import { DEFAULT_COUNTRY_CODE, getCountryConfig } from "./config.js";

// Diccionario central de textos para autenticacion y etiquetas compartidas de la UI.
const UI_TEXTS = {
  es: {
    authWelcome: "Bienvenido",
    authWelcomeBack: "Bienvenido de nuevo",
    authCopy: "Crea tu cuenta o inicia sesión.",
    authContinueCopy: "Ingresa a tu cuenta para continuar.",
    authName: "Nombre",
    authEmail: "Correo electrónico",
    authCountry: "País",
    authPassword: "Contraseña",
    authConfirmPassword: "Confirmar contraseña",
    authLogin: "Iniciar sesión",
    authSignup: "Registrarse",
    authSignupAction: "Crear cuenta",
    authRecover: "¿Olvidaste tu contraseña?",
    authNoAccount: "¿No tienes una cuenta?",
    authOr: "o",
    authPasswordShow: "Mostrar contraseña",
    authPasswordHide: "Ocultar contraseña",
    authPasswordRequired: "Escribe tu contraseña.",
    authNameRequired: "Escribe tu nombre para registrarte.",
    authNameMin: "El nombre debe tener al menos 2 caracteres.",
    authNameMax: "El nombre no puede exceder los 100 caracteres.",
    authNamePattern: "El nombre solo puede contener letras, espacios, apóstrofes y guiones.",
    authCountryRequired: "Selecciona un país para registrarte.",
    authCountryInvalid: "El país seleccionado no es válido.",
    authEmailRequired: "Completa el correo electrónico y la contraseña.",
    authEmailInvalid: "Ingresa un correo electrónico válido.",
    authEmailMax: "El correo electrónico es demasiado largo.",
    authPasswordMin: "La contraseña debe tener al menos 6 caracteres.",
    authPasswordMax: "La contraseña no puede exceder los 128 caracteres.",
    authPasswordSpaces: "La contraseña no puede contener espacios.",
    authPasswordUpper: "La contraseña debe incluir al menos una letra mayúscula.",
    authPasswordLower: "La contraseña debe incluir al menos una letra minúscula.",
    authPasswordNumber: "La contraseña debe incluir al menos un número.",
    authPasswordSpecial: "La contraseña debe incluir al menos un carácter especial (!@#$%, etc.).",
    authPasswordMismatch: "Las contraseñas no coinciden.",
    authLoginError: "Correo o contraseña incorrectos.",
    authEmailTaken: "Este correo ya está registrado.",
    authEmailConfirm: "Debes confirmar tu correo antes de iniciar sesión.",
    authPasswordRule: "La contraseña no cumple los requisitos mínimos.",
    authGenericError: "Ocurrió un error. Inténtalo nuevamente.",
    authRecoverEmailRequired: "Escribe tu correo electrónico para enviarte el enlace.",
    authLoginLoading: "Iniciando sesión...",
    authLoginSuccess: "Sesión iniciada correctamente.",
    authSignupLoading: "Creando cuenta...",
    authSignupSuccessLoggedIn: "Cuenta creada y sesión iniciada.",
    authSignupSuccessConfirm: "Cuenta creada. Revisa tu correo para confirmar tu registro.",
    authRecoverLoading: "Enviando correo de recuperación...",
    authRecoverSuccess: "Te enviamos un correo para recuperar tu contraseña.",
    authResetTitle: "Crea una nueva contraseña",
    authResetCopy: "Escribe una contraseña segura para volver a entrar.",
    authResetSubmit: "Guardar nueva contraseña",
    authResetLoading: "Guardando contraseña...",
    authResetSuccess: "Contraseña actualizada correctamente.",
    authResetRequired: "Abre el enlace de recuperación desde tu correo para cambiar la contraseña.",
    authSessionRequired: "Inicia sesión o regístrate para acceder a tus datos.",
    authSessionClosed: "La sesión se cerró. Vuelve a iniciar sesión.",
    authNameEmpty: "Escribe un nombre.",
    authNameSaveError: "No se pudo guardar el nombre.",
    authNameSaved: "Nombre actualizado.",
    authLogoutError: "No se pudo cerrar sesión.",
    uiEditGarmentName: "Editar nombre de la prenda",
    uiDeleteBlock: "Eliminar este bloque",
    uiAddRow: "Agregar fila",
    uiDeleteRow: "Eliminar fila",
    uiPrice: "PRECIO",
    uiDelete: "ELIMINAR",
    uiPriceAutomatic: "Precio automático",
    uiPriceOwn: "Precio propio",
    uiAddExtraMoney: "Agregar dinero extra",
    uiSubtractAdvance: "Restar adelanto",
    uiEditBlockName: "Editar nombre del bloque",
    uiDeleteFabricBlock: "Eliminar bloque de telas",
    uiAddFabricRow: "Agregar fila de tela",
    uiDeleteFabricRow: "Eliminar fila de tela",
    uiRolls: "Rollos",
    uiKgPerRoll: "Kg por rollo",
    uiPricePerKg: "Precio por kilo",
    uiTotalRolls: "Total rollos",
    uiTotalPrice: "Precio total",
    uiSummary: "RESUMEN GENERAL",
    uiGrandTotalCost: "Total compra",
    uiGrandTotalRolls: "Total rollos",
    uiGrandTotalKg: "Total kilos",
    uiTotalGarments: "Total prendas",
  },
  //portuguese translations
  pt: {
    authWelcome: "Bem-vindo",
    authWelcomeBack: "Bem-vindo de volta",
    authCopy: "Crie sua conta ou entre.",
    authContinueCopy: "Entre na sua conta para continuar.",
    authName: "Nome",
    authEmail: "E-mail",
    authCountry: "País",
    authPassword: "Senha",
    authConfirmPassword: "Confirmar senha",
    authLogin: "Entrar",
    authSignup: "Cadastrar-se",
    authSignupAction: "Criar conta",
    authRecover: "Esqueceu sua senha?",
    authNoAccount: "Ainda não tem uma conta?",
    authOr: "ou",
    authPasswordShow: "Mostrar senha",
    authPasswordHide: "Ocultar senha",
    authPasswordRequired: "Digite sua senha.",
    authNameRequired: "Escreva seu nome para se cadastrar.",
    authNameMin: "O nome deve ter pelo menos 2 caracteres.",
    authNameMax: "O nome não pode exceder 100 caracteres.",
    authNamePattern: "O nome só pode conter letras, espaços, apóstrofos e hífens.",
    authCountryRequired: "Selecione um país para se cadastrar.",
    authCountryInvalid: "O país selecionado não é válido.",
    authEmailRequired: "Preencha o e-mail e a senha.",
    authEmailInvalid: "Insira um e-mail válido.",
    authEmailMax: "O e-mail é muito longo.",
    authPasswordMin: "A senha deve ter pelo menos 6 caracteres.",
    authPasswordMax: "A senha não pode exceder 128 caracteres.",
    authPasswordSpaces: "A senha não pode conter espaços.",
    authPasswordUpper: "A senha deve incluir pelo menos uma letra maiúscula.",
    authPasswordLower: "A senha deve incluir pelo menos uma letra minúscula.",
    authPasswordNumber: "A senha deve incluir pelo menos um número.",
    authPasswordSpecial: "A senha deve incluir pelo menos um caractere especial (!@#$%, etc.).",
    authPasswordMismatch: "As senhas não coincidem.",
    authLoginError: "E-mail ou senha incorretos.",
    authEmailTaken: "Este e-mail já está cadastrado.",
    authEmailConfirm: "Você precisa confirmar seu e-mail antes de entrar.",
    authPasswordRule: "A senha não atende aos requisitos mínimos.",
    authGenericError: "Ocorreu um erro. Tente novamente.",
    authRecoverEmailRequired: "Informe seu e-mail para receber o link.",
    authLoginLoading: "Entrando...",
    authLoginSuccess: "Sessão iniciada com sucesso.",
    authSignupLoading: "Criando conta...",
    authSignupSuccessLoggedIn: "Conta criada e sessão iniciada.",
    authSignupSuccessConfirm: "Conta criada. Verifique seu e-mail para confirmar o cadastro.",
    authRecoverLoading: "Enviando e-mail de recuperação...",
    authRecoverSuccess: "Enviamos um e-mail para você recuperar sua senha.",
    authResetTitle: "Crie uma nova senha",
    authResetCopy: "Digite uma senha segura para entrar novamente.",
    authResetSubmit: "Salvar nova senha",
    authResetLoading: "Salvando senha...",
    authResetSuccess: "Senha atualizada com sucesso.",
    authResetRequired: "Abra o link de recuperação enviado ao seu e-mail para alterar a senha.",
    authSessionRequired: "Entre ou crie uma conta para acessar seus dados.",
    authSessionClosed: "A sessão foi encerrada. Entre novamente.",
    authNameEmpty: "Informe um nome.",
    authNameSaveError: "Não foi possível salvar o nome.",
    authNameSaved: "Nome atualizado.",
    authLogoutError: "Não foi possível sair.",
    uiEditGarmentName: "Editar nome da peça",
    uiDeleteBlock: "Excluir este bloco",
    uiAddRow: "Adicionar linha",
    uiDeleteRow: "Excluir linha",
    uiPrice: "PREÇO",
    uiDelete: "EXCLUIR",
    uiPriceAutomatic: "Preço automático",
    uiPriceOwn: "Preço próprio",
    uiAddExtraMoney: "Adicionar dinheiro extra",
    uiSubtractAdvance: "Descontar adiantamento",
    uiEditBlockName: "Editar nome do bloco",
    uiDeleteFabricBlock: "Excluir bloco de tecido",
    uiAddFabricRow: "Adicionar linha de tecido",
    uiDeleteFabricRow: "Excluir linha de tecido",
    uiRolls: "Rolos",
    uiKgPerRoll: "Kg por rolo",
    uiPricePerKg: "Preço por quilo",
    uiTotalRolls: "Total de rolos",
    uiTotalPrice: "Preço total",
    uiSummary: "RESUMO GERAL",
    uiGrandTotalCost: "Total da compra",
    uiGrandTotalRolls: "Total de rolos",
    uiGrandTotalKg: "Total de quilos",
    uiTotalGarments: "Total de peças",
  },
};

// Obtiene un texto traducido segun pais, usuario o metadata disponible.
export function getUiText(key, value = null) {
  const countryCode =
    typeof value === "string"
      ? value
      : value?.user_metadata?.country ||
        value?.user_metadata?.country_code ||
        value?.country ||
        DEFAULT_COUNTRY_CODE;
  const language = getCountryConfig(countryCode).language || "es";
  return UI_TEXTS[language]?.[key] || UI_TEXTS.es[key] || key;
}
